#!/usr/bin/env python

import os
from subprocess import check_call

_dirname = os.path.dirname

REPO_ROOT = _dirname(_dirname(os.path.abspath(__file__)))

os.chdir(os.path.join(REPO_ROOT))


def run(command):
    return check_call(command, shell=True)


run('pytest -v --cov --cov-append --cov-report=term-missing')
